apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "1001"
  name: wonderwall
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  redis:
    - instance: sessions
      access: readwrite
  envFrom:
    - secret: wonderwall
  accessPolicy:
    outbound:
      rules:
       -  application: echo
       -  application: helseid-nav-test
      external:
        - host: helseid-sts.test.nhn.no
  image:   ghcr.io/nais/wonderwall:latest
  liveness:
    path: /oauth2/ping
    initialDelay: 60
  readiness:
    path: /oauth2/ping
    initialDelay: 60
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - https://wonderwall-helse.ekstern.dev.nav.no
  resources:
    limits:
      memory: 8192Mi
    requests:
      cpu: 250m
      memory: 4096Mi
  env:
    - name: WONDERWALL_REDIS_PASSWORD
      value: $(REDIS_PASSWORD_SESSIONS)
    - name: WONDERWALL_REDIS_USERNAME
      value: $(REDIS_USERNAME_SESSIONS)
    - name: WONDERWALL_REDIS_URI
      value: $(REDIS_URI_SESSIONS)
    - name: WONDERWALL_UPSTREAM_HOST
      value: echo
    - name: WONDERWALL_BIND_ADDRESS
      value: $(BIND_ADDRESS)
    - name: WONDERWALL_INGRESS
      value: https://wonderwall-helse.ekstern.dev.nav.no
    - name: WONDERWALL_OPENID_WELL_KNOWN_URL
      value: https://helseid-sts.test.nhn.no/.well-known/openid-configuration
    - name: WONDERWALL_AUTO_LOGIN
      value: "true"
    - name: WONDERWALL_OPENID_CLIENT_ID
      value: 90112420-3cc1-4452-9daa-cb1e32947ac4
