apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    annotations:
        nais.io/read-only-file-system: "false"
        nais.io/run-as-user: "1001"
    name: helseid-nav-test
    namespace: helseopplysninger
    labels:
        team: helseopplysninger
spec:
    azure:
        application:
            enabled: true
    accessPolicy:
        outbound:
            external:
                -   host: b27apvl220.preprod.local
                    ports:
                        -  name: mq
                        -  port: 1413
                        -  protocol: TCP
                -   host: {{wshost}}
                -   host: {{stshost}}
                -   host: youtube.com
                -   host: {{aareg}}
                -   host: {{ereg}}
    observability:
        tracing:
            enabled: true
    port: 8080
    image: {{image}}
    liveness:
        path: /actuator/health/liveness
        initialDelay: 60
    readiness:
        path: /actuator/health/readiness
        initialDelay: 60
    prometheus:
        enabled: true
        path: /actuator/prometheus
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 50
    ingresses:
        - {{ingress}}
    resources:
        limits:
            memory: 8192Mi
        requests:
            cpu: 250m
            memory: 4096Mi
    env:
        -   name: stshost
            value: {{stshost}}
        -   name:   wshost
            value: {{wshost}}
        -   name: env
            value: {{env}}
        -   name: clientid
            value: {{clientid}}
        -   name: aareg
            value: {{aareg}}
        - name: ereg
          value: {{ereg}}
    envFrom:
        -   secret: helseid
        -   secret: fastlege