management:
   health:
    ping:
      enabled: false
    diskspace:
      enabled: false
   endpoint:
      health:
        show-details: always
        show-components: always
      env:
        show-values: always
      configprops:
        show-values: always
   endpoints:
     web:
       exposure:
        include: '*'
spring:
  application:
    name: helseid-nav-test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${helse-id.issuer}
      client:
        registration:
          pdl:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            client-id: ${azure.app.client.id}
            client-secret: ${azure.app.client.secret}
            provider: aad
            scope:
              - api://${env}-fss.pdl.pdl-api/.default
          arbeidsforhold:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            client-id: ${azure.app.client.id}
            client-secret: ${azure.app.client.secret}
            provider: aad
            scope:
              - api://dev-fss.arbeidsforhold.aareg-services-nais-q1/.default
          helse-id:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            client-id:  ${clientid}
            client-name: NAV Helseopplysninger
            scope:
              - profile
              - openid
              - helseid://scopes/identity/assurance_level
              - helseid://scopes/identity/pid
              - helseid://scopes/identity/security_level
              - helseid://scopes/hpr/hpr_number
              - nhn:flr-public/read
        provider:
          aad:
            issuer-uri: ${azure.openid.config.issuer}
          helse-id:
            issuer-uri: ${helse-id.issuer}
  threads:
    virtual:
      enabled: true

adresse:
  url: https://${wshost}/v1/AR/Basic
  username: ${fastlege.username}
  password: ${fastlege.password}

arbeidsforhold:
  base-uri: https://${aareg}

organisasjon:
  base-uri: https://${ereg}

helse-id:
  issuer: https://${stshost}

fastlege:
    url: https://${wshost}/v2/flr/Basic

authserver:
    url: https://${stshost}
ibm:
  mq:
    channel: Q1_HELSEID
    user: srvhelseid
    password: j28uqTrxOpUeYCAcwv1IAn
    queue-manager: MQLS02
    application-name: ${spring.application.name}
    conn-name: ${dialogmelding.host}(1413)
pdl:
  base-uri: https://pdl-api.${env}-fss-pub.nais.io/graphql

dialogmelding:
    request: QA.Q414.IU03_UTSENDING
    response: QA.Q1_HELSEID.IU03_UTSENDING_REPLY