helse-id:
  issuer: https://${host}
fastlege:
    url: https://ws-at.test.nhn.no/v2/flr/Basic
adresse:
  url: https://ws-at.test.nhn.no/v1/AR/Basic
  username: ${fastlege.username}
  password: ${fastlege.password}
arbeidsforhold:
  base-uri: https://aareg-services-q1.dev-fss-pub.nais.io
organisasjon:
  base-uri: https://ereg-services-q1.dev-fss-pub.nais.io
