management:
   health:
    ping:
      enabled: false
    diskspace:
      enabled: false
   endpoint:
      health:
        show-details: always
        show-components: always
      env:
        show-values: always
      configprops:
        show-values: always
   endpoints:
     web:
       exposure:
        include: '*'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${helse-id.issuer}
      client:
        registration:
          helse-id:
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: "private_key_jwt"
            authorization-grant-type: "authorization_code"
            client-id:  ${clientid}
            client-name: "NAV Helseopplysninger"
            scope:
              - "profile"
              - "openid"
              - "helseid://scopes/identity/assurance_level"
              - "helseid://scopes/identity/pid"
              - "helseid://scopes/identity/security_level"
              - "helseid://scopes/hpr/hpr_number"
              - "nhn:flr-public/read"
              - "hdir:felleskodeverk.api/kodeverk"
              - "hdir:felleskodeverk.api/kodeverdier"
        provider:
          helse-id:
            issuer-uri: ${helse-id.issuer}


adresse:
  username: ${fastlege.username}
  password: ${fastlege.password}

arbeidsforhold:
  base-uri: https://${aareg}

organisasjon:
  base-uri: https://${ereg}

helse-id:
  issuer: https://${stshost}