name: Build and test
on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    
jobs:
  bygg:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      packages: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.kompiler.outputs.image }}
    steps:
      - name: Sjekker ut kode
        uses: actions/checkout@v4

      - name: Setter tag-navn
        run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login GAR
        uses: nais/login@v0
        with:
          project_id: ${{vars.NAIS_MANAGEMENT_PROJECT_ID}}
          identity_provider: ${{secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER}}
          team: helseopplysninger

      - name: Setter opp Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Kompilerer, bygger  og pusher image
        id: kompiler
        run: |
          echo "image=${{env.IMAGE}}:${{env.TAG}}" >> $GITHUB_OUTPUT
          ./mvnw -Dspring.profiles.active=local -DGAR_TOKEN=${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} -Djib.to.tags=latest,${TAG} -Drevision=${TAG}  package jib:build  
          echo "DIGEST=$(cat target/jib-image.digest)" >> $GITHUB_ENV
