name: Deploy kafka DLT topic

on:
  push:
    branches:
      - main
    paths:
      - .nais/topics/**
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
    strategy:
      matrix:
        cluster: [ dev-gcp ]
        topic: [ main,main.dlt,main.retry ]

    name: Deploy ${{matrix.topic}} til ${{matrix.cluster}}
    runs-on: ubuntu-latest
    environment: ${{matrix.cluster}}:helseopplysninger
    env:
      PRINT_PAYLOAD: true
    steps:
      - uses: actions/checkout@v4
      - name: deploy ${{matrix.topic}} to ${{matrix.cluster}}
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{matrix.cluster}}
          RESOURCE: .nais/topics/${{matrix.topic}}/topic.yaml
          VARS: .nais/topics/${{matrix.topic}}/${{matrix.cluster}}.yaml
          PRINT_PAYLOAD: true
